
""" 
To create python module from c++ scripts (lce.cc and ace_wrap.cxx created by swig).

setup() and extension() functions of distutils.core are used to create the module.

setup() : basic Distutils function.

Extension() : describes a single C or C++ module in an installation script.


usage : python3 setup.py  build_ext --inplace

"""
from distutils.core import setup, Extension

INCLUDES =['../larq_compute_engine/tflite/cc','-I.','../third_party/tensorflow',
'../third_party/tensorflow/tensorflow/lite/'
'../third_party/tensorflow/tensorflow/lite/tools/make/downloads/',
'../third_party/tensorflow/tensorflow/lite/tools/make/downloads/eigen',
'../third_party/tensorflow/tensorflow/lite/tools/make/downloads/absl',
'../third_party/tensorflow/tensorflow/lite/tools/make/downloads/gemmlowp',
'../third_party/tensorflow/tensorflow/lite/tools/make/downloads/ruy',
'../third_party/tensorflow/tensorflow/lite/tools/make/downloads/neon_2_sse',
'../third_party/tensorflow/tensorflow/lite/tools/make/downloads/farmhash/src',
'../third_party/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include',
'../third_party/tensorflow/tensorflow/lite/tools/make/downloads/fp16/include',
'/usr/local/include/opencv4']
libraries = ['stdc++','pthread','m','z','dl','opencv_core','opencv_highgui',
'opencv_imgcodecs','opencv_imgproc','opencv_videoio']

args = ['-O3', '-DNDEBUG','-fPIC','--std=c++14' ]
extra_objects = ['../third_party/tensorflow/tensorflow/lite/tools/make/gen/linux_aarch64/lib/libtensorflow-lite.a',
   '../third_party/tensorflow/tensorflow/lite/tools/make/gen/linux_aarch64/obj/larq_compute_engine/tflite/kernels/bconv2d.o',
   '../third_party/tensorflow/tensorflow/lite/tools/make/gen/linux_aarch64/obj/larq_compute_engine/tflite/kernels/quantization.o',
   '../third_party/tensorflow/tensorflow/lite/tools/make/gen/linux_aarch64/obj/larq_compute_engine/tflite/kernels/bmaxpool.o']
fib_module = Extension(
   '_LCE',
   include_dirs = INCLUDES,
   library_dirs=['/usr/local/lib','../third_party/tensorflow/tensorflow/lite/tools/make/gen/linux_aarch64/lib/','/usr/local/cuda/lib64'],
   libraries=libraries,
   extra_compile_args= args,
   language = "c++",
   extra_objects = extra_objects,
   sources=['lce_wrap.cxx', 'lce.cc'], # lce_wrap.cxx is going to be generated by swig
)

setup (
	name        = 'LCE',
	version     = '0.0',
	author      = "GreenAI",
	description = "LCE swig",
	ext_modules = [fib_module],
	py_modules  = ["LCE"], # name of module that we're going import
)

